name: Create Ubuntu container and expose SSH port with Ngrok

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t ubuntu-ssh .

      - name: Start Serveo
        run: |
            ssh -T -o StrictHostKeyChecking=no -R vps:22:localhost:22 serveo.net

